###############################################################################
# Pin mapping
###############################################################################
#set_property PACKAGE_PIN J21 [get_ports DB_SCL]
#set_property PACKAGE_PIN J22 [get_ports DB_SDA]
#set_property IOSTANDARD LVCMOS18 [get_ports DB_SCL]
#set_property IOSTANDARD LVCMOS18 [get_ports DB_SDA]

set_property PACKAGE_PIN J16 [get_ports TCXO_DAC_SCLK]
set_property PACKAGE_PIN K16 [get_ports TCXO_DAC_SYNC_N]
set_property PACKAGE_PIN J15 [get_ports TCXO_DAC_SDIN]
set_property IOSTANDARD LVCMOS33 [get_ports TCXO_DAC_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports TCXO_DAC_SYNC_N]
set_property IOSTANDARD LVCMOS33 [get_ports TCXO_DAC_SDIN]

set_property PACKAGE_PIN K17 [get_ports TCXO_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports TCXO_CLK]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets TCXO_CLK]




set_property PACKAGE_PIN G14 [get_ports VCRX1_V1]
set_property PACKAGE_PIN C20 [get_ports VCRX1_V2]
set_property PACKAGE_PIN A20 [get_ports VCRX2_V1]
set_property PACKAGE_PIN E17 [get_ports VCRX2_V2]
set_property PACKAGE_PIN B20 [get_ports VCTX1_V1]
set_property PACKAGE_PIN B19 [get_ports VCTX1_V2]
set_property PACKAGE_PIN D18 [get_ports VCTX2_V1]
set_property PACKAGE_PIN D19 [get_ports VCTX2_V2]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX1_V1]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX1_V2]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX2_V1]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX2_V2]
set_property IOSTANDARD LVCMOS33 [get_ports VCTX2_V1]
set_property IOSTANDARD LVCMOS33 [get_ports VCTX2_V2]
set_property IOSTANDARD LVCMOS33 [get_ports VCTX1_V1]
set_property IOSTANDARD LVCMOS33 [get_ports VCTX1_V2]


set_property PACKAGE_PIN T10 [get_ports {CAT_CTRL_IN[0]}]
set_property PACKAGE_PIN Y12 [get_ports {CAT_CTRL_IN[1]}]
set_property PACKAGE_PIN Y13 [get_ports {CAT_CTRL_IN[2]}]
set_property PACKAGE_PIN V11 [get_ports {CAT_CTRL_IN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_IN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAT_CTRL_IN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAT_CTRL_IN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAT_CTRL_IN[3]}]

set_property PACKAGE_PIN T11 [get_ports {CAT_CTRL_OUT[0]}]
set_property PACKAGE_PIN T14 [get_ports {CAT_CTRL_OUT[1]}]
set_property PACKAGE_PIN T15 [get_ports {CAT_CTRL_OUT[2]}]
set_property PACKAGE_PIN T17 [get_ports {CAT_CTRL_OUT[3]}]
set_property PACKAGE_PIN T19 [get_ports {CAT_CTRL_OUT[4]}]
set_property PACKAGE_PIN T20 [get_ports {CAT_CTRL_OUT[5]}]
set_property PACKAGE_PIN U13 [get_ports {CAT_CTRL_OUT[6]}]
set_property PACKAGE_PIN V13 [get_ports {CAT_CTRL_OUT[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_CTRL_OUT[7]}]


set_property PACKAGE_PIN R14 [get_ports CAT_SCLK]
set_property PACKAGE_PIN P18 [get_ports CAT_CS]
set_property PACKAGE_PIN P15 [get_ports CAT_MOSI]
set_property PACKAGE_PIN R19 [get_ports CAT_MISO]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_CS]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_MISO]


set_property PACKAGE_PIN P14 [get_ports CAT_TXNRX]
set_property PACKAGE_PIN N17 [get_ports CAT_RESET]
set_property PACKAGE_PIN R18 [get_ports CAT_ENABLE]
set_property PACKAGE_PIN P16 [get_ports CAT_ENAGC]
set_property PACKAGE_PIN U20 [get_ports CAT_SYNC]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_TXNRX]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_RESET]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_ENABLE]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_ENAGC]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_SYNC]


set_property PACKAGE_PIN N18 [get_ports CAT_FB_CLK]
set_property PACKAGE_PIN Y16 [get_ports CAT_TX_FRAME]
set_property PACKAGE_PIN Y19 [get_ports {CAT_P1_D[0]}]
set_property PACKAGE_PIN Y18 [get_ports {CAT_P1_D[1]}]
set_property PACKAGE_PIN V18 [get_ports {CAT_P1_D[2]}]
set_property PACKAGE_PIN V17 [get_ports {CAT_P1_D[3]}]
set_property PACKAGE_PIN W20 [get_ports {CAT_P1_D[4]}]
set_property PACKAGE_PIN V20 [get_ports {CAT_P1_D[5]}]
set_property PACKAGE_PIN R17 [get_ports {CAT_P1_D[6]}]
set_property PACKAGE_PIN R16 [get_ports {CAT_P1_D[7]}]
set_property PACKAGE_PIN W19 [get_ports {CAT_P1_D[8]}]
set_property PACKAGE_PIN W18 [get_ports {CAT_P1_D[9]}]
set_property PACKAGE_PIN W16 [get_ports {CAT_P1_D[10]}]
set_property PACKAGE_PIN V16 [get_ports {CAT_P1_D[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_FB_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_TX_FRAME]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P1_D[11]}]


set_property PACKAGE_PIN N20 [get_ports CAT_DATA_CLK]
set_property PACKAGE_PIN U18 [get_ports CAT_RX_FRAME]
set_property PACKAGE_PIN Y14 [get_ports {CAT_P0_D[0]}]
set_property PACKAGE_PIN W14 [get_ports {CAT_P0_D[1]}]
set_property PACKAGE_PIN U12 [get_ports {CAT_P0_D[2]}]
set_property PACKAGE_PIN T12 [get_ports {CAT_P0_D[3]}]
set_property PACKAGE_PIN U15 [get_ports {CAT_P0_D[4]}]
set_property PACKAGE_PIN U14 [get_ports {CAT_P0_D[5]}]
set_property PACKAGE_PIN U17 [get_ports {CAT_P0_D[6]}]
set_property PACKAGE_PIN T16 [get_ports {CAT_P0_D[7]}]
set_property PACKAGE_PIN W13 [get_ports {CAT_P0_D[8]}]
set_property PACKAGE_PIN V12 [get_ports {CAT_P0_D[9]}]
set_property PACKAGE_PIN W15 [get_ports {CAT_P0_D[10]}]
set_property PACKAGE_PIN V15 [get_ports {CAT_P0_D[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_DATA_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports CAT_RX_FRAME]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CAT_P0_D[11]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CAT_DATA_CLK]


set_property PACKAGE_PIN Y11 [get_ports GPS_PPS]
set_property PACKAGE_PIN W11 [get_ports PPS_EXT_IN]
set_property PACKAGE_PIN U9 [get_ports ONSWITCH_DB]
set_property PACKAGE_PIN U10 [get_ports {PL_GPIO[0]}]
set_property PACKAGE_PIN T9 [get_ports {PL_GPIO[1]}]
set_property PACKAGE_PIN U8 [get_ports {PL_GPIO[2]}]
set_property PACKAGE_PIN W9 [get_ports {PL_GPIO[3]}]
set_property PACKAGE_PIN V7 [get_ports {PL_GPIO[4]}]
set_property PACKAGE_PIN T5 [get_ports {PL_GPIO[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports PPS_EXT_IN]
set_property IOSTANDARD LVCMOS33 [get_ports GPS_PPS]
set_property IOSTANDARD LVCMOS33 [get_ports ONSWITCH_DB]
set_property IOSTANDARD LVCMOS33 [get_ports {PL_GPIO[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PL_GPIO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PL_GPIO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PL_GPIO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PL_GPIO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PL_GPIO[5]}]

set_property PULLDOWN true [get_ports {PL_GPIO[0]}]
set_property PULLDOWN true [get_ports {PL_GPIO[1]}]
set_property PULLDOWN true [get_ports {PL_GPIO[2]}]
set_property PULLDOWN true [get_ports {PL_GPIO[3]}]
set_property PULLDOWN true [get_ports {PL_GPIO[4]}]
set_property PULLDOWN true [get_ports {PL_GPIO[5]}]

